
#  springcloud config 测试
spring:
  profiles:
    active:
      - dev

---
spring:
  profiles: dev # 开发环境
  application:
    name: cloud-config-chai-dev
---
spring:
  profiles: test # 测试环境
  application:
    name: cloud-config-chai-test

